#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# DCL-Lite Unit Test Worker
# Anthony J. Borla (ajborla@bigpond.com)
# ----------------------------------------------------------------------------

runtest() {
  :
}

testcut() {
  :
}

#
# Perform tests. Value of `status` set to 1 (error) if any test fails
#
runtests() {
  status=0
  while IFS= read -r testargs; do
    runtest "${testargs}" || status=1
  done < /dev/stdin

  return $status
}

