#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# DCL-Lite Unit Test Worker
# Anthony J. Borla (ajborla@bigpond.com)
# ----------------------------------------------------------------------------

runtest() {
  :
}

testcut() {
  :
}

runtests() {
  :
}

