#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# DCL-Lite Unit Test Runner [leap.com]
# Anthony J. Borla (ajborla@bigpond.com)
# ----------------------------------------------------------------------------

#
# Load unit test routines
#
. DCLUNIT

#
# Perform tests. Overall test status returned
#
runtests << EOF
Year not divisible by 4: common year^==^0^false^leap 2015
Year divisible by 2, not divisible by 4 in common year^==^0^false^leap 1970
Year divisible by 4, not divisible by 100: leap year^==^0^true^leap 1996
Year divisible by 4 and 5 is still a leap year^==^0^true^leap 1960
Year divisible by 100, not divisible by 400: common year^==^0^false^leap 2100
Year divisible by 100 but not by 3 is still not a leap year^==^0^false^leap 1900
Year divisible by 400: leap year^==^0^true^leap 2000
Year divisible by 400 but not by 125 is still a leap year^==^0^true^leap 2400
Year divisible by 200, not divisible by 400 in common year^==^0^false^leap 1800
No input should return an error^==^1^ERROR: Invalid arguments. USAGE: @leap year^leap
Too many arguments should return an error^==^1^ERROR: Invalid arguments. USAGE: @leap year^leap 2016 4562 4566
Float number input should return an error^==^1^ERROR: Only positive numbers allowed. USAGE: @leap year^leap "2016.54"
Alpha input should return an error^==^1^ERROR: Only positive numbers allowed. USAGE: @leap year^leap "abcd"
EOF
