#!/usr/bin/env bash

# ----------------------------------------------------------------------------
# DCL-Lite Unit Test Runner [raindrops.com]
# Anthony J. Borla (ajborla@bigpond.com)
# ----------------------------------------------------------------------------

#
# Load unit test routines
#
. DCLUNIT

#
# Perform tests. Overall test status returned
#
runtests << EOF
The sound for 1 is 1^==^0^1^raindrops 1
The sound for 3 is Pling^==^0^Pling^raindrops 3
The sound for 5 is Plang^==^0^Plang^raindrops 5
The sound for 7 is Plong^==^0^Plong^raindrops 7
The sound for 6 is Pling as it has a factor 3^==^0^Pling^raindrops 6
2 to the power 3 does not make a raindrop sound as 3 is the exponent not the base^==^0^8^raindrops 8
The sound for 9 is Pling as it has a factor 3^==^0^Pling^raindrops 9
The sound for 10 is Plang as it has a factor 5^==^0^Plang^raindrops 10
The sound for 14 is Plong as it has a factor of 7^==^0^Plong^raindrops 14
The sound for 15 is PlingPlang as it has factors 3 and 5^==^0^PlingPlang^raindrops 15
The sound for 21 is PlingPlong as it has factors 3 and 7^==^0^PlingPlong^raindrops 21
The sound for 25 is Plang as it has a factor 5^==^0^Plang^raindrops 25
The sound for 27 is Pling as it has a factor 3^==^0^Pling^raindrops 27
The sound for 35 is PlangPlong as it has factors 5 and 7^==^0^PlangPlong^raindrops 35
The sound for 49 is Plong as it has a factor 7^==^0^Plong^raindrops 49
The sound for 52 is 52^==^0^52^raindrops 52
The sound for 105 is PlingPlangPlong as it has factors 3, 5 and 7^==^0^PlingPlangPlong^raindrops 105
The sound for 3125 is Plang as it has a factor 5^==^0^Plang^raindrops 3125
The sound for a missing value is 0 (call fails)^==^1^0^raindrops
The sound for too many values is 0 (call fails)^==^1^0^raindrops 45 67 12
The sound for a negative value is 0 (call fails)^==^1^0^raindrops -34
The sound for a non-number is 0 (call fails)^==^1^0^raindrops "abc"
EOF

